services:
  app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/syssoftintegra/service-email:latest
    # ports:
      # - 6507:80
    container_name: sysintegra-email
    restart: always
    networks:
      - luis

networks:
  luis:
    external: true