name: Docker CI - SysSoftIntegra Email

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    env:
      ECR_IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/syssoftintegra/service-email:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cat > .env <<EOL
          NODE_ENV="${{secrets.NODE_ENV}}"
          PORT="${{secrets.PORT}}"
          APP_URL="${{secrets.APP_URL}}"
          CORS_ORIGIN="${{secrets.CORS_ORIGIN}}"

          AWS_REGION="${{secrets.AWS_REGION}}"
          AWS_ACCESS_KEY_ID="${{secrets.AWS_ACCESS_KEY_ID}}"
          AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY}}"

          SMTP_USER="${{secrets.SMTP_USER}}"
          SMTP_PASS="${{secrets.SMTP_PASS}}"

          S3_BUCKET_NAME="${{secrets.S3_BUCKET_NAME}}"
          EOL

      - name: Build Docker image
        run: docker compose -f docker-compose.build.yml build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1 

      - name: Tag sysintegra-email image
        run: docker tag sysintegra-email $ECR_IMAGE_URI

      - name: Push sysintegra-email image to ECR
        run: docker push $ECR_IMAGE_URI

  deploy-to-runs-on:
    name: Deploy to Production Server
    runs-on: self-hosted
    needs: build-and-push

    env:
      CONTAINER_NAME: sysintegra-email
      IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/syssoftintegra/service-email:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download image from Amazon ECR
        run: docker pull $IMAGE_NAME

      - name: Create and run container
        run: docker compose -f docker-compose.prod.yml up -d
      
      - name: Clean up local Docker images
        run: docker image prune -af || true

  clean-ecr-images:
    name: Clear up old images in ECR
    runs-on: ubuntu-latest
    needs: deploy-to-runs-on

    steps: 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Delete old images from ECR
        run: |
          REPO="syssoftintegra/service-email"
          TAG="latest"

          aws ecr list-images \
          --repository-name "$REPO" \
          --query "imageIds[?type(imageTag)==null || imageTag!='${TAG}']" \
          --output json > images.json

          COUNT=$(jq length images.json)

          if [ "$COUNT" -gt 0 ]; then
            echo "🗑️ Cleaning up $COUNT old images from $REPO..."
            
            aws ecr batch-delete-image \
              --repository-name "$REPO" \
              --image-ids file://images.json
          else
            echo "✅ There are no old images to delete from $REPO."
          fi
